type Query {
    apod(apiKey: String!, date: String!): Apod!
    apods(apiKey: String!, startDate: String!, endDate: String!): [Apod!]!
}

type Apod {
    date: String!,
    explanation: String!,
    hdurl: String!,
    mediaType: String!,
    serviceVersion: String!,
    title: String!,
    url: String!
}
