type Query {
    today(apiKey: String!, thumbs: Boolean): Apod!
    apodByDate(apiKey: String!, date: String!, thumbs: Boolean): Apod!
    apodsByDate(apiKey: String!, startDate: String!, endDate: String, thumbs: Boolean): [Apod!]!
    randomApods(apiKey: String!, count: Int!, thumbs: Boolean): [Apod!]!
}
