name: Docker Image CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/na-gql-wrap:latest

      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
          && echo ${{ secrets.DOCKERHUB_USERNAME }}/na-gql-wrap:latest
